### ISSUE TITLE
Merging with identicon-styles

### ISSUE THREAD

**Issue by fgaz** [mrkkrp/identicon#11]
https://github.com/fgaz/identicon-styles

What about it?

I don't really know if it's a good idea. Some default styles are nice, but it's more code and one more dep (polyvariadic) for the ones who will not use them too.

**Comment by mrkkrp** [comment]
I think it's better to keep the "core" functionality in `identicon` and build upon it in other packages. That said, `identicon-styles` is nice, I'll mention it in the readme.

Do you intend to upload the package to Hackage?

**Comment by fgaz** [comment]
I wanted to upload it once I implement the gravatar-like style (which I didn't get around to do yet), but I'm starting to think that it's better to split identicon-styles in individual packages, one per style, so I do not impose unneeded compilation times to users. Then I could upload the squares one as identicon-style-squares.

**Comment by mrkkrp** [comment]
Just my personal opinion: it would be easier to maintain one package with a collection of styles than many little packages.

Ping me here when the package(s) is(are) on Hackage, I'll add a note about them in the readme.

**Comment by fgaz** [comment]
@mrkkrp 
At last I uploaded it https://hackage.haskell.org/package/identicon-style-squares

I chose to separate them but I didn't do the other style yet, so it's only that package

**Comment by mrkkrp** [comment]
Mentioned it in the readme!

**Comment by fgaz** [comment]
Thanks!
